version: "3.0"
services:
  order:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/www
  mysql:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tool
    ports:
      - "3306:3306"
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8024:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
